[wip] デザインの修正
twin-te/twinte-sponsorship pull request #92
Opened 2022-04-23 10:07 UTC by szk18

https://github.com/twin-te/twinte-sponsorship/issues/26 を見直している

2022-04-23 10:28 UTC, szk18 commented
figma で管理してたんだっけか．今も生きてるのであれば見たいかも @takonasu

2022-04-23 11:42 UTC, szk18 commented
サイドバー 崩れる．．．

2022-04-23 12:10 UTC, szk18 commented
サイドバーの幅を固定にした

2022-04-23 13:49 UTC, szk18 commented
> ↑一時的にありがとうございました！
> って表示するだけにしといた

`/success` はバックエンドの修正が終わるまで寄付金額を表示しないようにするべきか？今は0円って表示される

2022-04-23 23:48 UTC, takonasu requested changes
figma のリンクはSlackで送付しておきます。
モバイル版のメニューバーが崩れてしまっているのでその修正をお願いしますmm


![image](https://user-images.githubusercontent.com/37821819/164949751-1052fa17-06ac-45d8-b5c3-680befb9a27a.png)

2022-04-23 23:51 UTC, szk18 commented
あーサイドバーの横幅を固定にしちゃったかから，チェックありがとう．直します

2022-04-24 00:11 UTC, szk18 commented
@takonasu いったんこのpull requestはこれでお願いします．

2022-04-24 07:14 UTC, takonasu approved these changes
OK！ありがとう！

2022-04-24 07:15 UTC, merged