Next
twin-te/twinte-sponsorship pull request #93
Opened 2022-04-24 12:16 UTC by szk18

2022-05-06 03:22 UTC, takonasu commented
今までのが色々やばかったのでNext.jsに移行
見た目や挙動を確認してほしいです！
（CORSの制限があるので注意）

2022-05-08 14:05 UTC, KanadeNishizawa requested changes
ありがとうございます！
デザインデータ上で考慮されておらず後出しで申し訳ないのですが、全ページのこのコンテンツ部分にmax-width: 800pxの設定をお願いしたいです…！
<img width="460" alt="スクリーンショット 2022-05-08 23 00 35" src="https://user-images.githubusercontent.com/48097323/167299980-82d30c41-3e79-4755-a4e5-0d4fd00ee34c.png">

2022-05-08 15:33 UTC, szk18 commented
@KanadeNishizawa 
確認ありがとうございます！
`max-width` を追加しました 👍  https://github.com/twin-te/twinte-sponsorship/pull/93/commits/78d116f8bd918c3754e1211ac1131069f26d5ec3

2022-05-08 17:50 UTC, HikaruEgashira approved these changes
LGTM！

2022-05-09 06:22 UTC, KanadeNishizawa approved these changes
対応いただき助かりました！
パーペキです、ありがとうございます！

2022-05-09 12:38 UTC, merged

2022-05-09 12:44 UTC, szk18 commented
ログインがうまくできんね．`{ withCredentials: true }` を設定してないのが悪い説があるので後ほど @takonasu が対応してくれます

2022-05-09 12:46 UTC, szk18 commented
```
{message: "cookie 'twinte_session' required", errors: []}
errors: []
message: "cookie 'twinte_session' required"
```
だそうです．

![image](https://user-images.githubusercontent.com/39793156/167412644-9b8064ad-eaa5-4396-9e1e-cf138e59b297.png)